[project]
name = "py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.3",
    "sb3-contrib>=2.7.1",
    "stable-baselines3>=2.7.1",
]
